src/objects/BPDCreds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Credentials for accessing the BPD API</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BPD Credentials</label>
</CustomObject>

src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Climate_Zone__c</fullName>
        <label>Climate Zone</label>
        <picklist>
            <picklistValues>
                <fullName>1A, Very Hot - Humid (Miami, FL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A, Hot - Humid (Houston, TX)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B, Hot - Dry (Phoenix, AZ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3A, Warm - Humid (Memphis, TN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3B, Warm - Dry (El Paso, TX)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3C, Warm - Marine (San Francisco, CA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4A, Mixed - Humid (Baltimore, MD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4B, Mixed - Dry (Albuquerque, NM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4C, Mixed - Marine (Salem, OR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5A, Cool - Humid (Chicago, IL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5B, Cool - Dry (Boise, ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6A, Cold - Humid (Burlington, VT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6B, Cold - Dry (Helena, MT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7, Very Cold (Duluth, MN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8, Subarctic (Fairbanks, AK)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facility_Subtype__c</fullName>
        <label>Facility Subtype</label>
        <picklist>
            <controllingField>Facility_Type__c</controllingField>
            <picklistValues>
                <fullName>Administrative/professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Financial Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/other financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Box (&gt; 50K sf)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College or university</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution/Shipping center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dormitory/fraternity/sorority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drama theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elementary/middle school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enclosed mall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment/culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire station/police station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funeral home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inpatient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical, non-diagnostic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motel or inn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Movie Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-mall other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-refrigerated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facility_Type__c</fullName>
        <label>Facility Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartment Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banquet Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comm Garage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenience store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grocery store/food market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laboratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactured Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Assembly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Religious worship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Floor_Area_Square_Meters__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Square Meters</description>
        <label>Floor Area</label>
        <precision>18</precision>
        <required>true</required>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heating__c</fullName>
        <label>Heating</label>
        <picklist>
            <picklistValues>
                <fullName>Boiler - Hot Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boiler - Steam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boiler - Uncategorized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Steam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Furnace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heat Pump - Air Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heat Pump - Uncategorized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heat Pump - Water Loop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perimeter Baseboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PTAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radiator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resistance Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lighting__c</fullName>
        <label>Lighting</label>
        <picklist>
            <picklistValues>
                <fullName>Compact Fluorescent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - T12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - T5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - T8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - Uncategorized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halogen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incandescent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mercury Vapor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metal Halide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other / Combination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sodium - High Pressure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sodium - Low Pressure</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>BN-{00000000}</displayFormat>
        <label>Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EUI_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>EUI Analyses</relationshipLabel>
        <relationshipName>EUI_Analyses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUI_Value__c</fullName>
        <label>EUI Value</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Filter_Type__c</fullName>
        <label>Filter Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Peer_Group__c</fullName>
        <label>Peer Group</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUI Analysis</label>
    <nameField>
        <displayFormat>EUIA-{00000000}</displayFormat>
        <label>EUI Analysis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EUI Analyses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BPDUtils.cls
public class BPDUtils {
	
	public static AnalyzeResponse peerAnalysisResponse(HttpRequest req){
		Http http = new Http();
		System.debug(req.getBody());
		HttpResponse res = http.send(req);
		System.debug(res.getBody());
		AnalyzeResponse peerResponse = (AnalyzeResponse)JSON.deserialize(res.getBody(), AnalyzeResponse.class);
		return peerResponse;
	}

	public static HttpRequest peerAnalysisRequest(String buildingString){
		HttpRequest req = new HttpRequest();
		req.setEndpoint('https://bpd.lbl.gov/api/v1/analyze/peers/?format=json');
		req.setMethod('POST');
		BPDCreds__c creds = BPDCreds__c.getInstance(); 
		req.setHeader('Content-type', 'application/json');
		req.setHeader('Authorization', 'ApiKey '+creds.username__c+':'+creds.api_key__c);
		req.setBody('{\"filters\": '+buildingString+'}');
		return req;
	}

	public static HttpRequest comparisonRequest(String filterString, String buildingSystem, String fromString, String toString){
		HttpRequest req = new HttpRequest();
		req.setEndpoint('https://bpd.lbl.gov/api/v1/analyze/compare/eui/?format=json');
		req.setMethod('POST');
		BPDCreds__c creds = BPDCreds__c.getInstance(); 
		req.setHeader('Content-type', 'application/json');
		req.setHeader('Authorization', 'ApiKey '+creds.username__c+':'+creds.api_key__c);
		req.setBody('{\"filters\": '+filterString+', \"building_system\": \"'+buildingSystem+'\", \"from\": \"'+fromString+'\", \"to\": \"'+toString+'\"}');
		return req;
	}

	@future(callout = true)
	public static void getPeerData(String buildingId){
		Building__c building = [Select Classification__c, Floor_Area_Square_Meters__c, Facility_Type__c, Facility_Subtype__c, Climate_Zone__c, Heating__c, Lighting__c from Building__c where Id = :buildingId];
		List<EUI_Analysis__c> analyses = new List<EUI_Analysis__c>();
		String timestamp = String.valueOf(Datetime.now());
		for(Integer i = 1; i < 10; i++){
			String buildingString = '';
			if(i == 1){
				buildingString = JSON.serializePretty(new Filter1(new Building__c(Classification__c = building.Classification__c, Floor_Area_Square_Meters__c = building.Floor_Area_Square_Meters__c)));
				HttpRequest peerReq = BPDUtils.peerAnalysisRequest(buildingString);
				AnalyzeResponse analysisResponse = BPDUtils.peerAnalysisResponse(peerReq);
				if(analysisResponse.totals.number_of_matching_buildings != 0){
					analyses.add(new EUI_Analysis__c(Building__c = buildingId, Filter_Type__c = 'Classification and Area - '+timestamp, EUI_Value__c = analysisResponse.eui_distribution.mean, Peer_Group__c = analysisResponse.totals.number_of_matching_buildings, Filter_Number__c = i, External_Id__c = buildingId+'-'+i));		
				}
			} else if (i == 2 && building.Facility_Type__c != null){
				buildingString = JSON.serializePretty(new Filter2(new Building__c(Classification__c = building.Classification__c, Floor_Area_Square_Meters__c = building.Floor_Area_Square_Meters__c, Facility_Type__c = building.Facility_Type__c, Facility_Subtype__c = building.Facility_Subtype__c)));
				HttpRequest peerReq = BPDUtils.peerAnalysisRequest(buildingString);
				AnalyzeResponse analysisResponse = BPDUtils.peerAnalysisResponse(peerReq);
				if(analysisResponse.totals.number_of_matching_buildings != 0){
					analyses.add(new EUI_Analysis__c(Building__c = buildingId, Filter_Type__c = 'Classification, Area and Facility Type - '+timestamp, EUI_Value__c = analysisResponse.eui_distribution.mean, Peer_Group__c = analysisResponse.totals.number_of_matching_buildings, Filter_Number__c = i, External_Id__c = buildingId+'-'+i));		
				}
			} else if (i == 3 && building.Climate_Zone__c != null && building.Facility_Type__c != null){
				buildingString = JSON.serializePretty(new Filter3(new Building__c(Classification__c = building.Classification__c, Floor_Area_Square_Meters__c = building.Floor_Area_Square_Meters__c, Facility_Type__c = building.Facility_Type__c, Facility_Subtype__c = building.Facility_Subtype__c, Climate_Zone__c = building.Climate_Zone__c)));
				HttpRequest peerReq = BPDUtils.peerAnalysisRequest(buildingString);
				AnalyzeResponse analysisResponse = BPDUtils.peerAnalysisResponse(peerReq);
				if(analysisResponse.totals.number_of_matching_buildings != 0){
					analyses.add(new EUI_Analysis__c(Building__c = buildingId, Filter_Type__c = 'Classification, Area, Facility Type and Climate Zone - '+timestamp, EUI_Value__c = analysisResponse.eui_distribution.mean, Peer_Group__c = analysisResponse.totals.number_of_matching_buildings, Filter_Number__c = i, External_Id__c = buildingId+'-'+i));		
				}
			} else if (i == 4 && building.Climate_Zone__c != null){
				buildingString = JSON.serializePretty(new Filter4(new Building__c(Classification__c = building.Classification__c, Facility_Type__c = building.Facility_Type__c, Facility_Subtype__c = building.Facility_Subtype__c)));
				HttpRequest peerReq = BPDUtils.peerAnalysisRequest(buildingString);
				AnalyzeResponse analysisResponse = BPDUtils.peerAnalysisResponse(peerReq);
				if(analysisResponse.totals.number_of_matching_buildings != 0){
					analyses.add(new EUI_Analysis__c(Building__c = buildingId, Filter_Type__c = 'Classification and Facility Type - '+timestamp, EUI_Value__c = analysisResponse.eui_distribution.mean, Peer_Group__c = analysisResponse.totals.number_of_matching_buildings, Filter_Number__c = i, External_Id__c = buildingId+'-'+i));		
				}
			} else if (i == 5 && building.Heating__c != null){
				buildingString = JSON.serializePretty(new Filter5(new Building__c(Classification__c = building.Classification__c, Heating__c = building.Heating__c)));
				HttpRequest peerReq = BPDUtils.peerAnalysisRequest(buildingString);
				AnalyzeResponse analysisResponse = BPDUtils.peerAnalysisResponse(peerReq);
				if(analysisResponse.totals.number_of_matching_buildings != 0){
					analyses.add(new EUI_Analysis__c(Building__c = buildingId, Filter_Type__c = 'Classification  and Heating - '+timestamp, EUI_Value__c = analysisResponse.eui_distribution.mean, Peer_Group__c = analysisResponse.totals.number_of_matching_buildings, Filter_Number__c = i, External_Id__c = buildingId+'-'+i));		
				}
			} else if (i == 6 && building.Heating__c != null){
				buildingString = JSON.serializePretty(new Filter6(new Building__c(Classification__c = building.Classification__c, Lighting__c = building.Lighting__c)));
				HttpRequest peerReq = BPDUtils.peerAnalysisRequest(buildingString);
				AnalyzeResponse analysisResponse = BPDUtils.peerAnalysisResponse(peerReq);
				if(analysisResponse.totals.number_of_matching_buildings != 0){
					analyses.add(new EUI_Analysis__c(Building__c = buildingId, Filter_Type__c = 'Classification  and Lighting - '+timestamp, EUI_Value__c = analysisResponse.eui_distribution.mean, Peer_Group__c = analysisResponse.totals.number_of_matching_buildings, Filter_Number__c = i, External_Id__c = buildingId+'-'+i));		
				}
			} else if (i == 7 && building.Heating__c != null){
				buildingString = JSON.serializePretty(new Filter7(new Building__c(Classification__c = building.Classification__c, Heating__c = building.Heating__c, Lighting__c = building.Lighting__c)));
				HttpRequest peerReq = BPDUtils.peerAnalysisRequest(buildingString);
				AnalyzeResponse analysisResponse = BPDUtils.peerAnalysisResponse(peerReq);
				if(analysisResponse.totals.number_of_matching_buildings != 0){
					analyses.add(new EUI_Analysis__c(Building__c = buildingId, Filter_Type__c = 'Classification, Heating and Lighting - '+timestamp, EUI_Value__c = analysisResponse.eui_distribution.mean, Peer_Group__c = analysisResponse.totals.number_of_matching_buildings, Filter_Number__c = i, External_Id__c = buildingId+'-'+i));		
				}
			}

		}
		
		upsert analyses External_Id__c;
	}

	public static String getBuildingString(Building__c building){
		return JSON.serializePretty(new Filter(building));
	}

}