src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>My_EUI__c</fullName>
        <formula>( ((My_Usage__c/90)*365) * 3.4121411565 )/ Floor_Area_Square_Meters__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>My EUI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>BN-{00000000}</displayFormat>
        <label>Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FilterComparison.cls
public with sharing class FilterComparison {
	public Decimal previousEUI {get; set;}
	public Decimal changeVal {get; set;}
	public Decimal newEUI {get; set;}
	public Decimal previousCost {get; set;}
	public Decimal newCost {get; set;}

	public FilterComparison(Building__c building, ComparisonResponse response){
		this.previousEUI = building.My_EUI__c;
		this.changeVal = response.histogram.change_ratio;
		this.newEUI = building.My_EUI__c * response.histogram.change_ratio;
		this.previousCost = building.Average_Building_Cost__c;
		this.newCost = building.Average_Building_Cost__c * (this.previousEUI/this.newEUI);
	}
}