src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facility_Subtype__c</fullName>
        <label>Facility Subtype</label>
        <picklist>
            <controllingField>Facility_Type__c</controllingField>
            <picklistValues>
                <fullName>Administrative/professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Financial Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/other financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Box (&gt; 50K sf)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College or university</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution/Shipping center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dormitory/fraternity/sorority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drama theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elementary/middle school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enclosed mall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment/culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire station/police station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funeral home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inpatient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical, non-diagnostic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motel or inn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Movie Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-mall other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-refrigerated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facility_Type__c</fullName>
        <label>Facility Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartment Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banquet Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comm Garage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenience store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grocery store/food market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laboratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactured Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Assembly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Religious worship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Floor_Area_Square_Meters__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Square Meters</description>
        <label>Floor Area</label>
        <precision>18</precision>
        <required>true</required>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>BN-{00000000}</displayFormat>
        <label>Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Filter2.cls
public class Filter2 {
	
	public List<String> classification_type;
	public FilterRange floor_area;
	public List<String> facility_type;

	public Filter2(Building__c building) {
		this.classification_type = new List<String>{building.classification__c};
		this.floor_area = new FilterRange(building.Floor_Area_Square_Meters__c.intValue(), (building.Floor_Area_Square_Meters__c*.2).intValue());
		this.facility_type = (building.facility_type__c != null) ? ((building.facility_subtype__c != null) ? new List<String>{building.facility_type__c + ' - '+building.facility_subtype__c} : new List<String>{building.facility_type__c}) : null;
	}

}