src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Climate_Zone__c</fullName>
        <label>Climate Zone</label>
        <picklist>
            <picklistValues>
                <fullName>1A, Very Hot - Humid (Miami, FL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2A, Hot - Humid (Houston, TX)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2B, Hot - Dry (Phoenix, AZ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3A, Warm - Humid (Memphis, TN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3B, Warm - Dry (El Paso, TX)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3C, Warm - Marine (San Francisco, CA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4A, Mixed - Humid (Baltimore, MD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4B, Mixed - Dry (Albuquerque, NM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4C, Mixed - Marine (Salem, OR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5A, Cool - Humid (Chicago, IL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5B, Cool - Dry (Boise, ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6A, Cold - Humid (Burlington, VT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6B, Cold - Dry (Helena, MT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7, Very Cold (Duluth, MN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8, Subarctic (Fairbanks, AK)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facility_Subtype__c</fullName>
        <label>Facility Subtype</label>
        <picklist>
            <controllingField>Facility_Type__c</controllingField>
            <picklistValues>
                <fullName>Administrative/professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/Financial Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank/other financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Box (&gt; 50K sf)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College or university</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution/Shipping center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dormitory/fraternity/sorority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drama theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elementary/middle school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enclosed mall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment/culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire station/police station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funeral home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High school</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inpatient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical, non-diagnostic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motel or inn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Movie Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-mall other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-refrigerated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facility_Type__c</fullName>
        <label>Facility Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartment Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banquet Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comm Garage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenience store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grocery store/food market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laboratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactured Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Assembly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Religious worship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Floor_Area_Square_Meters__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Square Meters</description>
        <label>Floor Area</label>
        <precision>18</precision>
        <required>true</required>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hour__c</fullName>
        <description>Per Week</description>
        <label>Hours Occupied</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lighting__c</fullName>
        <label>Lighting</label>
        <picklist>
            <picklistValues>
                <fullName>Compact Fluorescent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - T12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - T5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - T8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluorescent - Uncategorized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halogen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incandescent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mercury Vapor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metal Halide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other / Combination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sodium - High Pressure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sodium - Low Pressure</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_People__c</fullName>
        <label>Number of People</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year_Built__c</fullName>
        <label>Year Built</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>BN-{00000000}</displayFormat>
        <label>Building Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Filter.cls
public class Filter {
	
	public List<String> classification_type;
	public FilterRange floor_area;
	public List<String> facility_type;
	public List<String> climate_zone;
	public FilterRange year_built;
	public FilterRange hours_occupied;
	public FilterRange number_of_people;
	public List<String> state {get; set;}
	public List<String> zip_code {get; set;}
	public List<String> lighting {get; set;}
	public List<String> heating {get; set;}
	public List<String> cooling {get; set;}
	public List<String> window_glass_type {get; set;}
	public List<String> window_glass_layers {get; set;}
	public List<String> air_flow_control {get; set;}
	public FilterRange wall_insulation_r_value {get; set;}
	public List<String> roof_ceiling {get; set;}

	public Filter(Building__c building) {

		this.classification_type = new List<String>{building.classification__c};
		this.floor_area = new FilterRange(building.Floor_Area_Square_Meters__c.intValue(), (building.Floor_Area_Square_Meters__c*.2).intValue());
		this.facility_type = (building.facility_type__c != null) ? ((building.facility_subtype__c != null) ? new List<String>{building.facility_type__c + ' - '+building.facility_subtype__c} : new List<String>{building.facility_type__c}) : null;
		this.climate_zone = (building.climate_zone__c != null) ? new List<String>{building.climate_zone__c} : null;

		this.year_built = (building.year_built__c != null) ? new FilterRange(building.year_built__c.intValue(), 2) : null;
		this.hours_occupied = (building.hour__c != null) ? new FilterRange(building.hour__c.intValue(), 3) : null;
		this.number_of_people = (building.number_of_people__c != null) ? new FilterRange(building.number_of_people__c.intValue(), (building.Floor_Area_Square_Meters__c / 150).intValue()) : null;
		
		this.state = new List<String>{building.state__c};
		this.zip_code = new List<String>{String.valueOf(building.zip_code__c)};
		this.lighting = new List<String>{building.lighting__c};
		this.heating = new List<String>{building.heating__c};
		this.cooling = new List<String>{building.cooling__c};
		this.window_glass_type = new List<String>{building.window_glass_type__c};
		this.window_glass_layers = new List<String>{building.window_glass_layer__c};
		this.air_flow_control = new List<String>{building.air_flow_control__c};
		this.wall_insulation_r_value = (building.wall_insulation_r_value__c != null) ? new FilterRange(building.wall_insulation_r_value__c.intValue(), (building.wall_insulation_r_value__c*.2).intValue()) : null;
		this.roof_ceiling = new List<String>{building.roof_ceiling__c};
	}
}